# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
#    password: 050120877633
    password: 1911
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
  servlet:
    multipart:
      max-file-size: 20MB #设置springBoot上传到服务器的单个文件的最大大小
      max-request-size: 40MB #设置springBoot上传到服务器的请求的总大小
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.backend.entity
#  mapper-locations:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: phosphophyllite

